#ipfs_endpoint: /ip4/127.0.0.1/tcp/5001 #ipfs_endpoint must be in multiaddr format: https://github.com/multiformats/multiaddr#encoding
ipfs_endpoint: https://gateway.ipfs.io
hounds_metadata_endpoint: https://api.mutantdao.com/hounds/metadata
mayc_metadata_endpoint: https://boredapeyachtclub.com/api/mutants/
discord_bot_token: CARTEL_DISCORD_BOT_TOKEN #can set in env as CARTEL_DISCORD_BOT_TOKEN
image_processor_mappings:
    gm_mappings:
        Hound Lair: ./cartel/images/bowls/hound_lair.png
        Shipwreck: ./cartel/images/bowls/shipwreck.png
        Jungle: ./cartel/images/bowls/jungle.png
        Cave Entrance: ./cartel/images/bowls/cave_entrance.png
        Lab: ./cartel/images/bowls/lab.png
        Hideout: ./cartel/images/bowls/hideout.png
        Temple Room: ./cartel/images/bowls/temple_room.png
        Warehouse: ./cartel/images/bowls/warehouse.png
        Docks: ./cartel/images/bowls/docks.png
 
    nfd_merch_mappings:
        default: ./cartel/images/nfd/nfd_shirt.png
        default_flame: ./cartel/images/nfd/nfd_shirt_flame.png
        #xl: ./cartel/images/nfd/nfd_shirt_xl.png
        xl: ./cartel/images/nfd/nfd_pin.png
        xl_flame: ./cartel/images/nfd/nfd_pin.png
        xl_traits:
            gladiator: ""
            gorilla chest: ""
            k-9: ""
            samurai: "" 
            jet pack: ""
            abominable: "" 
            piranha: "" 
            deathbot rocket launcher: "" 
            tv: "" 
            kensei: "" 
            kensei gold: "" 
            gladiator gold: "" 
            frigid armor: "" 
            volcanic: "" 
            bionic rocket launcher: ""
            dragon scales: "" 
            haunted woods: "" 
            skull tunic: "" 
            skeletal armour: "" 
            cartel hoodie: ""
            ritual robe: ""
            mech saddle: ""
            blood bound: ""
        flame_traits:
            blue  flame: ""
            orange flame: ""
        hats:
            cartel hat: ./cartel/images/nfd/nfd_merch_hat.png
            cartel hat orange: ./cartel/images/nfd/nfd_merch_hat.png
    mayc_background_color_keys:
        #m1 and m2 bgs are same color
        yellow: f6c946
        aquamarine: 67cbab
        purple: 543f57
        orange: e08a3f
        blue: 5fbcdc
        new punk blue: 383e7b
        gray: 899b8d
        army green: d6cf12
    suit_mappings:
        masks:
            default: 
                chroma_key: ff00ff
                default: ./cartel/images/suits/masks/default_mask.png
                trait_mappings:
                    m1 stunt jacket: ./cartel/images/suits/masks/m1_stunt_jacket_mask.png
                    m1 service: ./cartel/images/suits/masks/m1_service_mask.png
                    m2 ww2 pilot helm: ./cartel/images/suits/masks/m2_ww2_pilot_helm_mask.png
                    m2 space suit: ./cartel/images/suits/masks/default_m2_spacesuit_and_service_mask.png
                    m2 service: ./cartel/images/suits/masks/default_m2_spacesuit_and_service_mask.png
            m1 bored: 
                chroma_key: ff00ff
                default: ./cartel/images/suits/masks/m1_bored_mask.png
                trait_mappings:
                    m1 stunt jacket: ./cartel/images/suits/masks/m1_bored_stunt_jacket_mask.png
                    m1 bored dagger: ./cartel/images/suits/masks/m1_bored_dagger_mask.png

            m2 rage:
                chroma_key: ff00ff
                default: ./cartel/images/suits/masks/m2_rage_mask.png
                trait_mappings:
                    m2 space suit: ./cartel/images/suits/masks/m2_rage_spacesuit_and_service_mask.png
                    m2 service: ./cartel/images/suits/masks/m2_rage_spacesuit_and_service_mask.png

            m2 dumbfounded:
                chroma_key: ff00ff
                default: ./cartel/images/suits/masks/m2_dumbfounded_mask.png
                trait_mappings:
                    m2 space suit: ./cartel/images/suits/masks/m2_dumbfounded_spacesuit_and_service_mask.png
                    m2 service: ./cartel/images/suits/masks/m2_dumbfounded_spacesuit_and_service_mask.png

            m2 bored:
                chroma_key: ff00ff
                default: ./cartel/images/suits/masks/m2_bored_mask.png
                trait_mappings:
                    m2 leather punk jacket: ./cartel/images/suits/masks/m2_bored_leather_punk_jacket_mask.png
                    m2 space suit: ./cartel/images/suits/masks/m2_bored_spacesuit_and_service_mask.png
                    m2 service: ./cartel/images/suits/masks/m2_bored_spacesuit_and_service_mask.png
            m2 jovial:
                chroma_key: ff00ff
                default: ./cartel/images/suits/masks/m2_jovial_mask.png
        skip_mask:
            - "m1 hawaiian"
            - "m1 bayc t black"
        suits:
            default:
                ape: ./cartel/images/suits/ape.png
                brown: ./cartel/images/suits/brown.png
                cartel: ./cartel/images/suits/cartel.png
                cartel comic: ./cartel/images/suits/cartel_comic.png
                cheetah: ./cartel/images/suits/cheetah.png
                demon: ./cartel/images/suits/demon.png
                kodamara: ./cartel/images/suits/kodamara.png
                luke: ./cartel/images/suits/luke.png
                mayc: ./cartel/images/suits/mayc.png
                nfd: ./cartel/images/suits/nfd.png
                red hat: ./cartel/images/suits/red_hat.png
                trippy: ./cartel/images/suits/trippy.png
                tux: ./cartel/images/suits/tux.png
            m2 bored:
                ape: ./cartel/images/suits/m2_bored_ape.png
                brown: ./cartel/images/suits/m2_bored_brown.png
                cartel: ./cartel/images/suits/m2_bored_cartel.png
                cartel comic: ./cartel/images/suits/m2_bored_cartel_comic.png
                cheetah: ./cartel/images/suits/m2_bored_cheetah.png
                demon: ./cartel/images/suits/m2_bored_demon.png
                kodamara: ./cartel/images/suits/m2_bored_kodamara.png
                luke: ./cartel/images/suits/m2_bored_luke.png
                mayc: ./cartel/images/suits/m2_bored_mayc.png
                nfd: ./cartel/images/suits/m2_bored_nfd.png
                red hat: ./cartel/images/suits/m2_bored_red_hat.png
                trippy: ./cartel/images/suits/m2_bored_trippy.png
                tux: ./cartel/images/suits/m2_bored_tux.png
    pledge_hands:
        mutant_hounds:
            default:
                colors:
                    orange: ./cartel/images/hands/default_hound_orange.png
                    white: ./cartel/images/hands/default_hound_white.png
                    black: ./cartel/images/hands/default_hound_black.png
        mayc:
            default:
                colors:
                    orange: ./cartel/images/hands/default_orange.png
                    white: ./cartel/images/hands/default_white.png
                    black: ./cartel/images/hands/default_black.png
            m1 hawaiian: 
               colors:
                    orange: ./cartel/images/hands/m1_hawaiian_orange.png
                    white: ./cartel/images/hands/m1_hawaiian_white.png
                    black: ./cartel/images/hands/m1_hawaiian_black.png
            m1 service: 
               colors:
                    orange: ./cartel/images/hands/m1_service_orange.png
                    white: ./cartel/images/hands/m1_service_white.png
                    black: ./cartel/images/hands/m1_service_black.png
            m2 service: 
               colors:
                    orange: ./cartel/images/hands/m2_service_orange.png
                    white: ./cartel/images/hands/m2_service_white.png
                    black: ./cartel/images/hands/m2_service_black.png
            m1 admiral coat: 
               colors:
                    orange: ./cartel/images/hands/m1_admiral_coat_orange.png
                    white: ./cartel/images/hands/m1_admiral_coat_white.png
                    black: ./cartel/images/hands/m1_admiral_coat_black.png
            m1 bayc t black: 
               colors:
                    orange: ./cartel/images/hands/m1_bayc_t_black_orange.png
                    white: ./cartel/images/hands/m1_bayc_t_black_white.png
                    black: ./cartel/images/hands/m1_bayc_t_black_black.png
            m1 caveman pelt: 
               colors:
                    orange: ./cartel/images/hands/m1_caveman_pelt_orange.png
                    white: ./cartel/images/hands/m1_caveman_pelt_white.png
                    black: ./cartel/images/hands/m1_caveman_pelt_black.png
            m1 hiphop: 
               colors:
                    orange: ./cartel/images/hands/m1_hiphop_orange.png
                    white: ./cartel/images/hands/m1_hiphop_white.png
                    black: ./cartel/images/hands/m1_hiphop_black.png
            m1 pimpcoat: 
               colors:
                    orange: ./cartel/images/hands/m1_pimpcoat_orange.png
                    white: ./cartel/images/hands/m1_pimpcoat_white.png
                    black: ./cartel/images/hands/m1_pimpcoat_black.png
            m1 puffy vest: 
               colors:
                    orange: ./cartel/images/hands/m1_puffy_vest_orange.png
                    white: ./cartel/images/hands/m1_puffy_vest_white.png
                    black: ./cartel/images/hands/m1_puffy_vest_black.png
            m1 stunt jacket: 
               colors:
                    orange: ./cartel/images/hands/m1_stunt_jacket_orange.png
                    white: ./cartel/images/hands/m1_stunt_jacket_white.png
                    black: ./cartel/images/hands/m1_stunt_jacket_black.png
            m2 black holes t: 
               colors:
                    orange: ./cartel/images/hands/m2_black_holes_t_orange.png
                    white: ./cartel/images/hands/m2_black_holes_t_white.png
                    black: ./cartel/images/hands/m2_black_holes_t_black.png
            m2 leather punk jacket: 
               colors:
                    orange: ./cartel/images/hands/m2_leather_punk_jacket_orange.png
                    white: ./cartel/images/hands/m2_leather_punk_jacket_white.png
                    black: ./cartel/images/hands/m2_leather_punk_jacket_black.png
            m2 smoking jacket: 
               colors:
                    orange: ./cartel/images/hands/m2_smoking_jacket_orange.png
                    white: ./cartel/images/hands/m2_smoking_jacket_white.png
                    black: ./cartel/images/hands/m2_smoking_jacket_black.png
            m2 space suit: 
               colors:
                    orange: ./cartel/images/hands/m2_space_suit_orange.png
                    white: ./cartel/images/hands/m2_space_suit_white.png
                    black: ./cartel/images/hands/m2_space_suit_black.png
            m2 stunt jacket:
                    orange: ./cartel/images/hands/m2_stunt_jacket_orange.png
                    white: ./cartel/images/hands/m2_stunt_jacket_white.png
                    black: ./cartel/images/hands/m2_stunt_jacket_black.png
    ape_bag:
        default: ./cartel/images/ape_bag/mayc_apebag_default.png
        m1 tongue out: ./cartel/images/ape_bag/mayc_apebag_m1tongueout.png
        m1 phoneme wah: ./cartel/images/ape_bag/mayc_apebag_m1phonemewah.png
        m1 grin gold grill: ./cartel/images/ape_bag/mayc_apebag_m1grillgoldgrin.png

    mayc_coffee_mug_mappings:
        liquids:
            coffee: ./cartel/images/coffee_mugs/liquids/coffee.png
            serum: ./cartel/images/coffee_mugs/liquids/serum.png
        steam:
            coffee: ./cartel/images/coffee_mugs/steam/coffee.png
            serum: ./cartel/images/coffee_mugs/steam/serum.png
        logos:
            albino asylum: ./cartel/images/coffee_mugs/logos/albino.png
            armoured guards: ./cartel/images/coffee_mugs/logos/armoured.png
            bionic army:  ./cartel/images/coffee_mugs/logos/bionics.png
            blood hounds: ./cartel/images/coffee_mugs/logos/bloodhound.png
            cartel: ./cartel/images/coffee_mugs/logos/cartel.png
            death pack: ./cartel/images/coffee_mugs/logos/deathpack.png
            deathbot army: ./cartel/images/coffee_mugs/logos/deathbots.png
            flesh eaters: ./cartel/images/coffee_mugs/logos/inside_out.png
            golem gang: ./cartel/images/coffee_mugs/logos/golem.png
            haunted howlers: ./cartel/images/coffee_mugs/logos/haunted.png
            laughing legion: ./cartel/images/coffee_mugs/logos/hyena_v2.png
            metal militia: ./cartel/images/coffee_mugs/logos/metal_militia.png
            midnight marauders: ./cartel/images/coffee_mugs/logos/midnight.png
            noisy syndicate: ./cartel/images/coffee_mugs/logos/noisy_syndicate.png
            royal hounds: ./cartel/images/coffee_mugs/logos/royals.png
            skull legion: ./cartel/images/coffee_mugs/logos/skulls.png
            trippy brigade: ./cartel/images/coffee_mugs/logos/trippy.png
            wolf pack: ./cartel/images/coffee_mugs/logos/wolf_pack.png
            zombie horde: ./cartel/images/coffee_mugs/logos/horde.png
        furs:
            m1 dark brown: ./cartel/images/coffee_mugs/m1_dark_brown.png
            m1 brown: ./cartel/images/coffee_mugs/m1_brown.png
            m1 black: ./cartel/images/coffee_mugs/m1_black.png
            m1 golden brown: ./cartel/images/coffee_mugs/m1_golden_brown.png
            m1 cream: ./cartel/images/coffee_mugs/m1_cream.png
            m1 tan: ./cartel/images/coffee_mugs/m1_tan.png
            m1 pink: ./cartel/images/coffee_mugs/m1_pink.png
            m1 gray: ./cartel/images/coffee_mugs/m1_gray.png
            m1 red: ./cartel/images/coffee_mugs/m1_red.png
            m1 blue: ./cartel/images/coffee_mugs/m1_blue.png
            m1 cheetah: ./cartel/images/coffee_mugs/m1_cheetah.png
            m1 white: ./cartel/images/coffee_mugs/m1_white.png
            m1 zombie:  ./cartel/images/coffee_mugs/m1_zombie.png
            m1 robot:  ./cartel/images/coffee_mugs/m1_robot.png
            m1 dmt:  ./cartel/images/coffee_mugs/m1_dmt.png
            m1 death bot:  ./cartel/images/coffee_mugs/m1_death_bot.png
            m1 noise: ./cartel/images/coffee_mugs/m1_noise.png
            m1 trippy:  ./cartel/images/coffee_mugs/m1_trippy.png
            m1 solid golid:  ./cartel/images/coffee_mugs/m1_gold.png
            m2 dark brown: ./cartel/images/coffee_mugs/m2_dark_brown.png
            m2 brown: ./cartel/images/coffee_mugs/m2_brown.png
            m2 black: ./cartel/images/coffee_mugs/m2_black.png
            m2 golden brown: ./cartel/images/coffee_mugs/m2_golden_brown.png
            m2 cream: ./cartel/images/coffee_mugs/m2_cream.png
            m2 tan: ./cartel/images/coffee_mugs/m2_tan.png
            m2 pink: ./cartel/images/coffee_mugs/m2_pink.png
            m2 gray: ./cartel/images/coffee_mugs/m2_gray.png
            m2 red: ./cartel/images/coffee_mugs/m2_red.png
            m2 blue: ./cartel/images/coffee_mugs/m2_blue.png
            m2 cheetah: ./cartel/images/coffee_mugs/m2_cheetah.png
            m2 white: ./cartel/images/coffee_mugs/m2_white.png
            m2 zombie:  ./cartel/images/coffee_mugs/m2_zombie.png
            m2 robot:  ./cartel/images/coffee_mugs/m2_robot.png
            m2 dmt:  ./cartel/images/coffee_mugs/m2_dmt.png
            m2 death bot:  ./cartel/images/coffee_mugs/m2_death_bot.png
            m2 noise: ./cartel/images/coffee_mugs/m2_noise.png
            m2 trippy:  ./cartel/images/coffee_mugs/m2_trippy.png
            m2 solid golid:  ./cartel/images/coffee_mugs/m2_gold.png
